---
- name: Use systemd-networkd for network
  copy:
    src: 20-wired.network
    dest: /etc/systemd/network/20-wired.network
    owner: root
    group: root
    mode: '0644'

- name: use systemd-resolved for DNS service
  ansible.builtin.file:
    src: /run/systemd/resolve/stub-resolv.conf
    dest: /etc/resolv.conf
    owner: root
    group: root
    state: link
    
- name: start systemd-resolved
  ansible.builtin.service:
    name: systemd-resolved
    state: started

- name: start systemd-networkd
  ansible.builtin.service:
    name: systemd-networkd
    state: started
