---
- name: install emacs
  pacman:
    name: emacs
    state: present
    update_cache: yes

- name: install Adobe Source Pro fonts
  pacman:
    name: adobe-source-code-pro-fonts
    state: present
    update_cache: yes

- name: get spacemacs
  ansible.builtin.git:
    repo: 'https://github.com/syl20bnr/spacemacs'
    dest: /home/hans/Downloads/spacemacs

